### ISSUE TITLE
Fix bug on saving picture in DB

### ISSUE THREAD

**Issue by sii-jmasset** [adierick/skillManager#28]
When an Admin uploads an User picture, this one isn't stored in DB but erases Admin's picture. So there's none new record created.

**Comment by adierick** [comment]
I think the issue comes from : we use the connected person rather than the selected person in case we are admin and we want to upload a picture for a specific user.
In this specific case, we must get the selected matricule and get this person.

**Comment by adierick** [comment]
" PersonController " in method " LoadPicture " you left :
Picture picture pictureService.getPicture = ( connected.getMatricule ());

I think when one is admin and that we are changing the profile of an employee , if you change the image of the collaborator, the controller will replace the image of the admin ( as it is the connected person ) and not the image of the employee that you are changing .

**Comment by adierick** [comment]
Issue fixed by @sii-jmasset
