### ISSUE TITLE
[PERSON] - Création / photo

### ISSUE THREAD

**Issue by adierick** [adierick/skillManager#32]
Lors de la création, il existe 2 bugs :
1. il n'y a pas d'images par défaut
2. si on fait un upload avant la sauvegarde de la création=> erreur

Il faut donc :
- [ ] afficher l'image par défaut du portrait  du collab
- [x] bloquer/griser le bouton l'upload et validation d'upload tant que la création du collab n'a pas été validé

**Comment by sii-jmasset** [comment]
Bonjour Aurélien, 

J'ai corrigé le trombi et réglé les bugs que tu avais levés 

Je te joins donc les fichiers modifiés : 
- PersonController.java 
- trombinoscope.jsp 
- editionperson.jsp 

J'ai également copié le fichier person-avatar1.png dans le dossier img 

Ces modifs effectuées, je réessaie d'installer l'application via Git pour que ce soit plus simple au niveau de la synchronisation des versions et continue les tâches définies. 

Cordialement, 

Julien 

----- Mail original -----

De: "adierick" <notifications@github.com> 
À: "adierick/skillManager" <skillManager@noreply.github.com> 
Cc: "sii-jmasset" <jmasset@lille.sii.fr> 
Envoyé: Lundi 30 Mars 2015 23:39:01 
Objet: [skillManager] [PERSON] - Création / photo (#32) 



Lors de la création, il existe 2 bugs : 
1. il n'y a pas d'images par défaut 
2. si on fait un upload avant la sauvegarde de la création=> erreur 

Il faut donc : 
[] afficher l'image par défaut du portrait du collab 
[] bloquer/griser le bouton l'upload et validation d'upload tant que la création du collab n'a pas été validé

**Comment by adierick** [comment]
Hello @sii-jmasset ,

Il reste un petit bug, lorsque je valide la création, l'image par défaut est perdu.
De même, si j'upload la photo j'ai une erreur:
Procédure de reproduction des erreurs :

- [ ] je rempli les données du nouvel utilisateur > sauvegarde => l'avatar par défaut disparaît
- [ ] juste après la sauvegarde de l'utilisateur, le bouton upload est dégrisé (c'est bien), mais si je fais l'action d'upload, j'ai une erreur

Peux tu voir pour corriger ces 2 points ?

Merci :)

**Comment by adierick** [comment]
Test ok :+1:
